### ISSUE TITLE
似乎不太好直接用于普通的CSC任务，需要先检测错误位置?

### ISSUE THREAD

**Issue by yongzhuo** [IgarashiAkatuki/CNMBert#1]
似乎不太好直接用于普通的CSC任务，需要先检测错误位置?

**Comment by IgarashiAkatuki** [comment]
目是这样的（逃
也有想过去加一个模块自动检测错误位置，但是最后训练下来发现准确率很惨，很容易把句子中的英文单词或者是一些并非拼音缩写的东西识别成"错误"，遂暂时搁置

**Comment by yongzhuo** [comment]
get，感谢回复
